### ISSUE TITLE
Замечания по паттерну "Наблюдатель"

### ISSUE THREAD

**Issue by alexey-malov** [iandreyshev/volgatech_ood_2018#3]
- [x] Дисплей, отображающий статистику, должен подсчитывать средние и граничные значения влажности, давления и температуры

**Comment by alexey-malov** [comment]
https://github.com/iandreyshev/volgatech_ood_2018/blob/e74b32f6dc9fb37ae44a8b5890c4a26a23921f09/Lab2-Observer/WeatherStation/src/main/kotlin/observer/Observable.kt#L17-L22

- [x] Есть подозрение, что удаление или добавление элементов из/в HashSet во время итерирования по коллекции не является безопасным. Напишите тест, который бы фейлился без необходимых исправлений

**Comment by alexey-malov** [comment]
https://github.com/iandreyshev/volgatech_ood_2018/blob/e74b32f6dc9fb37ae44a8b5890c4a26a23921f09/Lab2-Observer/PriorityWeatherStation/src/main/kotlin/observer/PriorityObservable.kt#L11-L13

- [x] Проверить в тестах, что два разных наблюдателя с одним и тем же приоритетом могут быть добавлены в качестве наблюдателей и оба получат уведомление, пусть даже в заранее неопределённом порядке.

**Comment by alexey-malov** [comment]
https://github.com/iandreyshev/volgatech_ood_2018/blob/e74b32f6dc9fb37ae44a8b5890c4a26a23921f09/Lab2-Observer/WeatherStationDuo/src/main/kotlin/observer/Observable.kt#L3-L20
- [x] Не нужно вводить ISubject. Вместо этого используйте сравнение ссылки на observable с нужной станцией.
```
class Display : IObserver<WeatherData>
{
   void Update(IObservable<WeatherData>& wd)
   {
       WeatherStation ws = (wd == mOuterStation) ? mOuterStation : mInnerStation;
       // Notification came from ws
   }
   WeatherStation mOuterStation;
   WeatherStation mInnerStationl;
};
```

**Comment by alexey-malov** [comment]
- [x] В задании №6 индикатор должен отображать информацию о погоде вне помещения с информацией о ветре, а внутри помещения - без ветра.

**Comment by iandreyshev** [comment]
- [x] Реализовать дополнительное задание. Вместо boost signals использовать RxJava.
